services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: >
<<<<<<< HEAD
        sh -c "python wait_for_db.py &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"

=======
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
>>>>>>> cd530ea (Add user model)

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A masters worker --loglevel=info

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=boceyim123
      - POSTGRES_DB=masters
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: 