web: gunicorn masters.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A masters worker --loglevel=info
beat: celery -A masters beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler