# Generated by Django 5.2.1 on 2025-06-20 23:23

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri və rəqəmləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ0-9\\s.,!?-]+$'), utils.validators.not_only_whitespace, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(default='Anonim hesab', max_length=20, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri və rəqəmləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ0-9\\s.,!?-]+$')]),
        ),
    ]
