stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
      apk add --no-cache openssh-client sshpass
      mkdir -p ~/.ssh
      ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts || true
  script:
    - |
      echo "Deploying to $SERVER_IP"
      sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "/usr/local/bin/deploy"
  only:
    - dev
    - main