# Generated by Django 5.2.1 on 2025-06-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['display_name']},
        ),
    ]
