# Generated by Django 5.2.1 on 2025-06-02 20:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dil adı')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/', verbose_name='İş şəkli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='cits',
            field=models.ManyToManyField(to='core.city', verbose_name='Fəaliyyət göstərdiyi regionlar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(choices=[('tam_ali', 'Tam ali'), ('natamam_ali', 'Natamam ali'), ('orta', 'Orta'), ('peshe', 'Peşə təhsili'), ('orta_ixtisas', 'Orta ixtisas təhsili')], default="Yoxdur", null=True, max_length=20, verbose_name='Təhsil səviyyəsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_speciality',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan əlifbasındakı hərflərə icazə verilir.', regex='^[A-Za-zƏəÖöĞğÜüÇçŞşİı]+$')], verbose_name='Təhsil üzrə ixtisas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(default=None, verbose_name='İş təcrübəsi (il ilə)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook linki'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram linki'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn linki'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Əlavə qeyd'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession_area',
            field=models.CharField(default=None, max_length=100, verbose_name='İxtisas sahəsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession_speciality',
            field=models.CharField(default=None, max_length=100, verbose_name='İxtisas üzrə peşə'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profil şəkli'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok linki'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son yenilənmə tarixi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Kişi'), ('FEMALE', 'Qadın')], max_length=6, verbose_name='Cins'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.ManyToManyField(to='users.language', verbose_name='Bildiyi dillər'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_images',
            field=models.ManyToManyField(blank=True, to='users.workimage', verbose_name='İşlərinə aid şəkillər'),
        ),
    ]
