# Generated by Django 5.2.1 on 2025-06-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_alter_customuser_profession_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='districts',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession_speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profession_masters', to='services.service'),
            preserve_default=False,
        ),
    ]
