# Generated by Django 5.2.1 on 2025-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_language_workimage_customuser_cits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(choices=[('1', 'Tam ali'), ('2', 'Natamam ali'), ('3', 'Orta'), ('4', 'Peşə təhsili'), ('5', 'Orta ixtisas təhsili')], default='Yoxdur', max_length=20, verbose_name='Təhsil səviyyəsi'),
        ),
    ]
