# Generated by Django 5.2.1 on 2025-06-14 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_districts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_profession',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan əlifbasındakı hərflərə icazə verilir.', regex='^(?=.*[A-Za-zƏəÖöĞğÜüÇçŞşİı])[A-Za-zƏəÖöĞğÜüÇçŞşİı\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_speciality',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan əlifbasındakı hərflərə icazə verilir.', regex='^(?=.*[A-Za-zƏəÖöĞğÜüÇçŞşİı])[A-Za-zƏəÖöĞğÜüÇçŞşİı\\s]+$')], verbose_name='Təhsil üzrə ixtisas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan əlifbasındakı hərflərə icazə verilir.', regex='^(?=.*[A-Za-zƏəÖöĞğÜüÇçŞşİı])[A-Za-zƏəÖöĞğÜüÇçŞşİı\\s]+$')], verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan əlifbasındakı hərflərə icazə verilir.', regex='^(?=.*[A-Za-zƏəÖöĞğÜüÇçŞşİı])[A-Za-zƏəÖöĞğÜüÇçŞşİı\\s]+$')], verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='note',
            field=models.TextField(blank=True, max_length=1500, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan əlifbasındakı hərflərə icazə verilir.', regex='^(?=.*[A-Za-zƏəÖöĞğÜüÇçŞşİı])[A-Za-zƏəÖöĞğÜüÇçŞşİı\\s]+$')], verbose_name='Əlavə qeyd'),
        ),
    ]
