# Generated by Django 5.2.1 on 2025-06-20 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_custom_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_profession',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri və rəqəmləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ0-9\\s.,!?-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_speciality',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri və rəqəmləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ0-9\\s.,!?-]+$')], verbose_name='Təhsil üzrə ixtisas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='note',
            field=models.TextField(blank=True, max_length=1500, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri və rəqəmləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ0-9\\s.,!?-]+$')], verbose_name='Əlavə qeyd'),
        ),
    ]
