# Generated by Django 5.2.1 on 2025-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_options_alter_district_options'),
        ('users', '0005_alter_customuser_custom_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.ManyToManyField(blank=True, related_name='district_masters', to='core.district', verbose_name='Bakı bölgələri'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='city_masters', to='core.city', verbose_name='Şəhərlər'),
        ),
    ]
