# Generated by Django 5.2.1 on 2025-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='İş təcrübəsi (il ilə)'),
        ),
    ]
