# Generated by Django 5.2.1 on 2025-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(choices=[('0', 'Yoxdur'), ('1', 'Tam ali'), ('2', 'Natamam ali'), ('3', 'Orta'), ('4', 'Peşə təhsili'), ('5', 'Orta ixtisas təhsili')], max_length=20, verbose_name='Təhsil səviyyəsi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(verbose_name='İş təcrübəsi (il ilə)'),
        ),
    ]
