# Generated by Django 5.2.1 on 2025-06-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_district_alter_customuser_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='district',
            new_name='districts',
        ),
    ]
