# Generated by Django 5.2.1 on 2025-06-22 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_district_customuser_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_profession',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Yalnız Azərbaycan hərfləri və rəqəmləri ilə yazılmalıdır.', regex='^[a-zA-ZəƏöÖüÜşŞçÇğĞıİ0-9\\s.,!?-]+$')]),
        ),
    ]
