# Generated by Django 5.2.1 on 2025-06-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cits',
            new_name='cities',
        ),
    ]
