# Generated by Django 5.2.1 on 2025-06-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_cits_customuser_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workimage',
            name='order',
        ),
    ]
