# Generated by Django 5.2.1 on 2025-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_custom_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
    ]
